### ISSUE TITLE
link to repo

### ISSUE THREAD

**Issue by willkg** [jmathies/util-process-top-crashes#2]
I've had a couple of instance where I wanted to look at the script that generates the site and I had to go hunting for the repo url.

It'd be great if the repo url was in the footer of the rendered pages.

I think that's as simple as adding an `a href` to `template.html`. Is that true? If so, I could do it.

**Comment by jmathies** [comment]
Hey Will!

I'll add that, need to do a checkin as my local copy has a number of
changes. Will get that done today or tomorrow.

Jim

**Comment by jmathies** [comment]
I've updated everything now. I'm still working on this, plan to improve the graphing (break it down by version info) and improve the meta data display in that header as well.
